name: Update Files JSON

on:
  push:
    branches:
      - main

jobs:
  update_files_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List text files
        id: list-files
        run: |
          echo "::set-output name=files::$(find . -name '*.txt' -type f -printf '%f\n')"

      - name: Update files.json
        run: |
          echo "{\"files\": [\"${{ join(steps.list-files.outputs.files, '", "') }}\"]}" > files.json
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add files.json
          git commit -m "Update files.json" --quiet
          git push origin main
